#### Tipos de Dados

In [3]:
#Inteiro

idade = 30
temperatura = -4
numeroGrande = 12345667

In [4]:
#float

peso = 91.2
temperatura = -4.5

In [5]:
#String

Nome = "Bruce"

numero_A = 1
numero_B = "1"

numero_A == numero_B

False

In [6]:
#Booleana

linguagem_1 = "python"
linguagem_2 = "java"

Resultado = linguagem_1 == linguagem_2

Resultado

verdadeiro = True
verdadeiro

falso = False
falso

False

#### Verificação de Tipo de dados

In [ ]:
#Verificação de tipo de dados de uma variável
print(type(linguagem_1))
print(type(Resultado))
print(type(idade))
print(type(peso))

<class 'str'>
<class 'bool'>
<class 'int'>
<class 'float'>

#### Exemplo de tipos diferentes de dados

In [8]:
inteiro = 52
flutuante = 3.5
texto = "texto"
lista = [1, 5, 6]
tupla = (1, 3)
dicionario = {'a':1, 'b':2, 'a': 2, 'b': 2}
booleano = True

#### Verificando

In [9]:
print(type(inteiro))    # <class 'int'>
print(type(flutuante))  # <class 'float'>
print(type(texto))      # <class 'str'>
print(type(lista))      # <class 'list'>
print(type(tupla))      # <class 'tuple'>
print(type(dicionario)) # <class 'dict'>
print(type(booleano))   # <class 'bool'>

<class 'int'>
<class 'float'>
<class 'str'>
<class 'list'>
<class 'tuple'>
<class 'dict'>
<class 'bool'>

#### Formatação de Strings

In [10]:
marca = "iphone 15"
lancamento = 2023
valor = 1299
taxaDolar = 4.95555555

#Forma Não otimizada:
print('O ' + marca + ' foi lançado em ' + str(lancamento))
print()

#Forma otimizada
print('O %s foi lançado em %d custano %d. Mas a taxa de consão de real para dolar é de R$%.2f para 1 dolar'%(marca, lancamento, valor, taxaDolar)) 
#As marcações são deixadas no texto para representarem as variáveis que podem ser inseridas posteriormente.

#Maracações para cada tipo de dados:
#string ->  %s
#Int ->     %d
#Float ->   %.(número de casas decimais)f

O iphone 15 foi lançado em 2023

O iphone 15 foi lançado em 2023 custano 1299. Mas a taxa de consão de real para dolar é de R$4.96 para 1 dolar

#### Format

In [ ]:
marca = "iphone 15"
lancamento = 2023
valor = 1299
taxaDolar = 4.95555555

#Opção utilizando o format:
print('O {0} foi lançado em {1} custano {2}. Mas a taxa de consão de real para dolar é de R${3:.2f} para 1 dolar'.format(marca, lancamento, valor, taxaDolar))
# Funciona atravez de um índice que conta a partir do 0 e pode ser atribuido respectivamente pela ordem estabelecida dentro da função.
# É possivel controlar as casas decimais do tipo float utilizando o ":" seguida da mesma abordagem anterior.

O iphone 15 foi lançado em 2023 custano 1299. Mas a taxa de consão de real para dolar é de R$4.96 para 1 dolar

In [12]:
#Outra alternativa com o format:
print(f'O {marca} foi lançado em {lancamento} custano {valor}. Mas a taxa de consão de real para dolar é de R${taxaDolar:.2f} para 1 dolar')
# Nesse método, ao invés de utilizar um ídice, utiliza-se a inserção da própria variável.

O iphone 15 foi lançado em 2023 custano 1299. Mas a taxa de consão de real para dolar é de R$4.96 para 1 dolar

#### Converção de dados

In [35]:
numero = 2
numero = float('2')
numero

# É possivel converter os dados principalmente em:
# String    -> str()
# Inteiro   -> int()
# Flutuante -> float()

2.0

#### Listas

In [14]:
minhaLista = []

nomeUsuario = ["Hugo", "José", "Luiz"]
idadeUsuario = [18, 19, 20]

nomeUsuario, idadeUsuario

(['Hugo', 'José', 'Luiz'], [18, 19, 20])

In [15]:
#Adicionar itens na lista
nomeUsuario.append("Tio Patinhas")
idadeUsuario.append(60)

nomeUsuario, idadeUsuario

(['Hugo', 'José', 'Luiz', 'Tio Patinhas'], [18, 19, 20, 60])

In [16]:
#Remover itens na lista
idadeUsuario.remove(idadeUsuario[2]) #Remover por índice
nomeUsuario.remove("Tio Patinhas")
nomeUsuario, idadeUsuario

(['Hugo', 'José', 'Luiz'], [18, 19, 60])

In [17]:
nomeUsuario, idadeUsuario

(['Hugo', 'José', 'Luiz'], [18, 19, 60])

In [18]:
#Encontrar valor em uma lista por um índice

idadeAlunos = [49, 50, 41, 39, 22, 30, 43, 45, 27, 18, 32, 24, 21, 48, 31]
idadeAlunos[10]

32

In [19]:
idadeAlunos = [49, 50, 41, 39, 22, 30, 43, 45, 27, 18, 32, 24, 21, 48, 31]

#da esquerda (valor positivo - começa em 0)
idadeAlunos[10]

#da direita (valor negativo - começa em -1)
idadeAlunos[-3]

21

In [44]:
idadeAlunos = [49, 50, 41, 39, 22, 30, 43, 45, 27, 18, 32, 24, 21, 48, 31]

#Buscar os primeiros itens

#da esquerda (valor positivo)
idadeAlunos[:4] #Conta a partir do 1

#da direita (valor negativo)
idadeAlunos[-3:]

[21, 48, 31]

In [21]:
idadeAlunos = [49, 50, 41, 39, 22, 30, 43, 45, 27, 18, 32, 24, 21, 48, 31]

#Buscar por um intervalo

idadeAlunos[4:10] #[traz o número contando a partir do 0 : traz o número contando a partir do 1] (realmente é confuso)

[22, 30, 43, 45, 27, 18]

In [22]:
idadeAlunos = [49, 50, 41, 39, 22, 30, 43, 45, 27, 18, 32, 24, 21, 48, 31]

#Acessar intervalo

idadeAlunos[0:9:2] #adiciona um intervalo

[49, 41, 22, 43, 27]

In [23]:
idadeAlunos = [49, 50, 41, 39, 22, 30, 43, 45, 27, 18, 32, 24, 21, 48, 31]
idadeAlunos

#Alterar valores

idadeAlunos[0] = 63
idadeAlunos

[63, 50, 41, 39, 22, 30, 43, 45, 27, 18, 32, 24, 21, 48, 31]

#### Tuplas

In [24]:
#Diferente das listas, as tuplas não podem ser alteradas posteriormente a sua declaração.

mesesDoAno = ('Jan', 'Feb', 'mar', 'Abr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec')

#Acessar valore (semlehandte as listas)
mesesDoAno[3:6]

('Abr', 'May', 'Jun')

#### Dicionarios

In [25]:
meuDicionario = {}
type(meuDicionario)

dict

In [26]:
usuario = {
    "hugo":18,
    "josé":19,
    "luiz":20
}

usuario

{'hugo': 18, 'josé': 19, 'luiz': 20}

In [27]:
#imprimindo apenas um item
usuario["josé"] #Retorna o valor correspondente ao nome

19

In [28]:
#Alterar valores

usuario["luiz"] = 21
usuario

{'hugo': 18, 'josé': 19, 'luiz': 21}

In [29]:
#Adicionar itens ao dicionario

usuario["João"] = 12
usuario

{'hugo': 18, 'josé': 19, 'luiz': 21, 'João': 12}

#### Criando uma lista de dicionarios

In [30]:
listaUsuarios = [
    {"nome": "Hugo", "idade": 18},
    {"nome": "José", "idade": 19},
    {"nome": "Luiz", "idade": 21},
    {"nome": "Pato", "idade": 30}
]

listaUsuarios

[{'nome': 'Hugo', 'idade': 18},
 {'nome': 'José', 'idade': 19},
 {'nome': 'Luiz', 'idade': 21},
 {'nome': 'Pato', 'idade': 30}]

In [31]:
import pandas as pd

In [32]:
df = pd.DataFrame(listaUsuarios)
df

   nome  idade
0  Hugo     18
1  José     19
2  Luiz     21
3  Pato     30

In [33]:
df.head(2)

   nome  idade
0  Hugo     18
1  José     19