In [59]:
import pandas as pd

### Pandas

In [60]:
#importando dados .csv

#file_name = 'Sales2022.csv' 
# Esta forma só funciona se oarquivo estiver na própria pasta

caminho_arquivo = r'D:\Progran Working\Python - Curso Bruce - Python Fundamentos\CursoPython\Sales2022.csv'
# quando for atribuir a variáveis endereços de pasta, onde a barra ("\") significa endereço, utiliza-se o "r" ("raw" significa "raiz")

df = pd.read_csv(caminho_arquivo) # df significa Data frame

In [61]:
df

,CustomerNumber,CustomerName,Country,State,City,PlantName,MaterialNumber,BusinessLine,Category,SalesDate,SalesOrder,Volume,Revenue
0,2431,CUSTOMER 2431,BR,BA,Alagoinhas,Itapuã,BL01-CA03-1040,Lubrificantes,CA03,2019-01-23 00:00:00,32172210,60,0.00
1,2431,CUSTOMER 2431,BR,BA,Alagoinhas,Itapuã,BL01-CA03-1040,Lubrificantes,CA03,2019-02-13 00:00:00,32192966,60,249.12
2,2431,CUSTOMER 2431,BR,BA,Alagoinhas,Itapuã,BL01-CA03-1040,Lubrificantes,CA03,2019-03-18 00:00:00,32213111,60,232.34
3,2431,CUSTOMER 2431,BR,BA,Alagoinhas,Itapuã,BL01-CA03-1040,Lubrificantes,CA03,2019-03-25 00:00:00,32213405,60,55.00
4,2431,CUSTOMER 2431,BR,BA,Alagoinhas,Itapuã,BL01-CA03-1040,Lubrificantes,CA03,2019-04-16 00:00:00,32234208,0,-287.34
...,...,...,...,...,...,...,...,...,...,...,...,...,...
29994,2524,CUSTOMER 2524,BR,PR,Araucária,Blumenau,BL01-CA06-1051,Lubrificantes,CA06,2019-06-24 00:00:00,32280793,522,106.96
29995,2524,CUSTOMER 2524,BR,PR,Araucária,Blumenau,BL01-CA06-1051,Lubrificantes,CA06,2019-07-29 00:00:00,32301515,522,107.48
29996,2524,CUSTOMER 2524,BR,PR,Araucária,Blumenau,BL01-CA06-1051,Lubrificantes,CA06,2019-08-01 00:00:00,32319797,522,158.32
29997,2524,CUSTOMER 2524,BR,PR,Araucária,Blumenau,BL01-CA06-1051,Lubrificantes,CA06,2019-08-12 00:00:00,32320856,261,53.75
29998,2524,CUSTOMER 2524,BR,PR,Araucária,Blumenau,BL01-CA06-1051,Lubrificantes,CA06,2019-08-30 00:00:00,32322965,261,53.73

In [62]:
df.head() #traz os primeiros itens da tabela (padrão 5)

,CustomerNumber,CustomerName,Country,State,City,PlantName,MaterialNumber,BusinessLine,Category,SalesDate,SalesOrder,Volume,Revenue
0,2431,CUSTOMER 2431,BR,BA,Alagoinhas,Itapuã,BL01-CA03-1040,Lubrificantes,CA03,2019-01-23 00:00:00,32172210,60,0.00
1,2431,CUSTOMER 2431,BR,BA,Alagoinhas,Itapuã,BL01-CA03-1040,Lubrificantes,CA03,2019-02-13 00:00:00,32192966,60,249.12
2,2431,CUSTOMER 2431,BR,BA,Alagoinhas,Itapuã,BL01-CA03-1040,Lubrificantes,CA03,2019-03-18 00:00:00,32213111,60,232.34
3,2431,CUSTOMER 2431,BR,BA,Alagoinhas,Itapuã,BL01-CA03-1040,Lubrificantes,CA03,2019-03-25 00:00:00,32213405,60,55.00
4,2431,CUSTOMER 2431,BR,BA,Alagoinhas,Itapuã,BL01-CA03-1040,Lubrificantes,CA03,2019-04-16 00:00:00,32234208,0,-287.34

#### Tipo de dados

In [63]:
df.dtypes # acessa o tipo dos dados armazenados em cada coluna

CustomerNumber      int64
CustomerName          str
Country               str
State                 str
City                  str
PlantName             str
MaterialNumber        str
BusinessLine          str
Category              str
SalesDate             str
SalesOrder          int64
Volume              int64
Revenue           float64
dtype: object

In [64]:
# Mudar o tipo de dados na importação 

data_type = { # dicionario que será utilizado para alterar por coluna o tipo de dados 
    'CustomerNumber': str,
    'SalesOrder': str
} 
# lembrando das boas praticas de estruturação dos dados que é transformar as keys em strings 
# # Isto é para que as colunas de id se manterem estáticas e não serem alteradas como valores nas análises

df = pd.read_csv(caminho_arquivo, dtype= data_type) 

# dtype é para definir o tipo das colunas que serão trazidas
# Ao inserir um dicionario neste campo com as especificações montadas acima, ela transforma o tipo dos campos específicos definidos. 

df.dtypes

CustomerNumber        str
CustomerName          str
Country               str
State                 str
City                  str
PlantName             str
MaterialNumber        str
BusinessLine          str
Category              str
SalesDate             str
SalesOrder            str
Volume              int64
Revenue           float64
dtype: object

In [65]:
# O pandas tbm tem suporte para o tipo data, mas a sua definição é feita de forma diferente

# Utiliza-se o 'parce_dates' para definir as colunas de datas

df = pd.read_csv(caminho_arquivo, dtype= data_type, parse_dates=['SalesDate']) # poderia ser uma variavel com uma lista das colunas ou uma lista direta desta forma com as colunas a serem tratadas como datas

df.dtypes

CustomerNumber               str
CustomerName                 str
Country                      str
State                        str
City                         str
PlantName                    str
MaterialNumber               str
BusinessLine                 str
Category                     str
SalesDate         datetime64[us]
SalesOrder                   str
Volume                     int64
Revenue                  float64
dtype: object

In [66]:
df.head() # É clara a mudança do tipo da formatação da coluna SalesDate em comparação com as consultas anteriores

,CustomerNumber,CustomerName,Country,State,City,PlantName,MaterialNumber,BusinessLine,Category,SalesDate,SalesOrder,Volume,Revenue
0,2431,CUSTOMER 2431,BR,BA,Alagoinhas,Itapuã,BL01-CA03-1040,Lubrificantes,CA03,2019-01-23,32172210,60,0.00
1,2431,CUSTOMER 2431,BR,BA,Alagoinhas,Itapuã,BL01-CA03-1040,Lubrificantes,CA03,2019-02-13,32192966,60,249.12
2,2431,CUSTOMER 2431,BR,BA,Alagoinhas,Itapuã,BL01-CA03-1040,Lubrificantes,CA03,2019-03-18,32213111,60,232.34
3,2431,CUSTOMER 2431,BR,BA,Alagoinhas,Itapuã,BL01-CA03-1040,Lubrificantes,CA03,2019-03-25,32213405,60,55.00
4,2431,CUSTOMER 2431,BR,BA,Alagoinhas,Itapuã,BL01-CA03-1040,Lubrificantes,CA03,2019-04-16,32234208,0,-287.34

#### Selecionar colunas

In [67]:
df.columns # Exibir colunas em formato de lista

Index(['CustomerNumber', 'CustomerName', 'Country', 'State', 'City',
       'PlantName', 'MaterialNumber', 'BusinessLine', 'Category', 'SalesDate',
       'SalesOrder', 'Volume', 'Revenue'],
      dtype='str')

In [68]:
# Variavel com uma lista das colunas desejadas
colunas = ['Country', 'State', 'City', 'PlantName', 'MaterialNumber', 'BusinessLine', 'Category', 'SalesDate', 'SalesOrder', 'Volume', 'Revenue'] 

df[colunas] # filtra pelas colunas definidas na lista

,Country,State,City,PlantName,MaterialNumber,BusinessLine,Category,SalesDate,SalesOrder,Volume,Revenue
0,BR,BA,Alagoinhas,Itapuã,BL01-CA03-1040,Lubrificantes,CA03,2019-01-23,32172210,60,0.00
1,BR,BA,Alagoinhas,Itapuã,BL01-CA03-1040,Lubrificantes,CA03,2019-02-13,32192966,60,249.12
2,BR,BA,Alagoinhas,Itapuã,BL01-CA03-1040,Lubrificantes,CA03,2019-03-18,32213111,60,232.34
3,BR,BA,Alagoinhas,Itapuã,BL01-CA03-1040,Lubrificantes,CA03,2019-03-25,32213405,60,55.00
4,BR,BA,Alagoinhas,Itapuã,BL01-CA03-1040,Lubrificantes,CA03,2019-04-16,32234208,0,-287.34
...,...,...,...,...,...,...,...,...,...,...,...
29994,BR,PR,Araucária,Blumenau,BL01-CA06-1051,Lubrificantes,CA06,2019-06-24,32280793,522,106.96
29995,BR,PR,Araucária,Blumenau,BL01-CA06-1051,Lubrificantes,CA06,2019-07-29,32301515,522,107.48
29996,BR,PR,Araucária,Blumenau,BL01-CA06-1051,Lubrificantes,CA06,2019-08-01,32319797,522,158.32
29997,BR,PR,Araucária,Blumenau,BL01-CA06-1051,Lubrificantes,CA06,2019-08-12,32320856,261,53.75
29998,BR,PR,Araucária,Blumenau,BL01-CA06-1051,Lubrificantes,CA06,2019-08-30,32322965,261,53.73

In [69]:
df[['MaterialNumber', 'Category']] # ao invés de uma variável com uma lista, podemos também a tribuir uma lista diretamente ao dataframe

       MaterialNumber Category
0      BL01-CA03-1040     CA03
1      BL01-CA03-1040     CA03
2      BL01-CA03-1040     CA03
3      BL01-CA03-1040     CA03
4      BL01-CA03-1040     CA03
...               ...      ...
29994  BL01-CA06-1051     CA06
29995  BL01-CA06-1051     CA06
29996  BL01-CA06-1051     CA06
29997  BL01-CA06-1051     CA06
29998  BL01-CA06-1051     CA06

[29999 rows x 2 columns]

In [70]:
# combinando com o metodo head

df[['MaterialNumber', 'Category']].head()

   MaterialNumber Category
0  BL01-CA03-1040     CA03
1  BL01-CA03-1040     CA03
2  BL01-CA03-1040     CA03
3  BL01-CA03-1040     CA03
4  BL01-CA03-1040     CA03

#### Filtrar dados

In [71]:
df['BusinessLine'].unique() 
# o unique mostra todos exemplares distintos daquela coluna (algo parecido com o DISTINCT faz no SQL e PowerBI))

<StringArray>
['Lubrificantes', 'Aditivos']
Length: 2, dtype: str

In [72]:
df['Category'].unique()

<StringArray>
['CA03', 'CA04', 'CA05', 'CA06', 'CA07', 'CA08', 'CA09', 'CA10', 'CA11',
 'CA01', 'CA02']
Length: 11, dtype: str

In [73]:
df['PlantName'].unique()

<StringArray>
['Itapuã', 'Betim', 'Aparecida de Goiânia', 'Blumenau', 'Sorocaba']
Length: 5, dtype: str

In [74]:
# filtrar por planta especifica

sorocaba_df = df[df['PlantName']=='Sorocaba']
sorocaba_df.head()

,CustomerNumber,CustomerName,Country,State,City,PlantName,MaterialNumber,BusinessLine,Category,SalesDate,SalesOrder,Volume,Revenue
13258,2464,CUSTOMER 2464,BR,SP,Araçariguama,Sorocaba,BL01-CA03-1039,Lubrificantes,CA03,2020-10-26,32608620,146,305.65
13259,2464,CUSTOMER 2464,BR,SP,Araçariguama,Sorocaba,BL01-CA03-1039,Lubrificantes,CA03,2021-01-06,32663300,146,133.95
13260,2464,CUSTOMER 2464,BR,SP,Araçariguama,Sorocaba,BL01-CA03-1040,Lubrificantes,CA03,2019-01-04,32171451,120,57.58
13261,2464,CUSTOMER 2464,BR,SP,Araçariguama,Sorocaba,BL01-CA03-1040,Lubrificantes,CA03,2019-01-22,32172133,120,57.58
13262,2464,CUSTOMER 2464,BR,SP,Araçariguama,Sorocaba,BL01-CA03-1040,Lubrificantes,CA03,2019-01-30,32172477,120,57.58

In [75]:
df[df['PlantName']=='Sorocaba'].head()

,CustomerNumber,CustomerName,Country,State,City,PlantName,MaterialNumber,BusinessLine,Category,SalesDate,SalesOrder,Volume,Revenue
13258,2464,CUSTOMER 2464,BR,SP,Araçariguama,Sorocaba,BL01-CA03-1039,Lubrificantes,CA03,2020-10-26,32608620,146,305.65
13259,2464,CUSTOMER 2464,BR,SP,Araçariguama,Sorocaba,BL01-CA03-1039,Lubrificantes,CA03,2021-01-06,32663300,146,133.95
13260,2464,CUSTOMER 2464,BR,SP,Araçariguama,Sorocaba,BL01-CA03-1040,Lubrificantes,CA03,2019-01-04,32171451,120,57.58
13261,2464,CUSTOMER 2464,BR,SP,Araçariguama,Sorocaba,BL01-CA03-1040,Lubrificantes,CA03,2019-01-22,32172133,120,57.58
13262,2464,CUSTOMER 2464,BR,SP,Araçariguama,Sorocaba,BL01-CA03-1040,Lubrificantes,CA03,2019-01-30,32172477,120,57.58

In [76]:
# Filtro sobre filtro

sorocaba_df[sorocaba_df["Revenue"]>=1000].head()

,CustomerNumber,CustomerName,Country,State,City,PlantName,MaterialNumber,BusinessLine,Category,SalesDate,SalesOrder,Volume,Revenue
13371,2464,CUSTOMER 2464,BR,SP,Araçariguama,Sorocaba,BL01-CA04-1042,Lubrificantes,CA04,2021-07-23,32778746,64,4652.00
13373,2464,CUSTOMER 2464,BR,SP,Araçariguama,Sorocaba,BL01-CA04-1042,Lubrificantes,CA04,2021-08-19,32797848,32,3247.00
13374,2464,CUSTOMER 2464,BR,SP,Araçariguama,Sorocaba,BL01-CA04-1042,Lubrificantes,CA04,2021-10-25,32837698,88,1257.54
13376,2464,CUSTOMER 2464,BR,SP,Araçariguama,Sorocaba,BL01-CA04-1042,Lubrificantes,CA04,2022-02-21,32899768,134,1193.00
13379,2464,CUSTOMER 2464,BR,SP,Araçariguama,Sorocaba,BL01-CA04-1042,Lubrificantes,CA04,2022-06-01,32988723,139,1089.18

In [77]:
# mais de uma condição
# sorocaba_df[() & ()]

sorocaba_df[(sorocaba_df["SalesDate"]>='2022-01-01') & (sorocaba_df["SalesDate"]<='2022-01-31')].sort_values(by='SalesDate', ascending=False)

# O sort_values(by='', ascending=False) é para ordenar (sort) os valores pela coluna ('by=') desejada, 
# quando definido o 'ascending=False' define que essa ordenção sera descendente (contrario de ascendente), ou seja, do maior para o menor

,CustomerNumber,CustomerName,Country,State,City,PlantName,MaterialNumber,BusinessLine,Category,SalesDate,SalesOrder,Volume,Revenue
20565,2491,CUSTOMER 2491,BR,SP,Araraquara,Sorocaba,BL02-CA01-2167,Aditivos,CA01,2022-01-31,32898029,0,828.00
24830,2503,CUSTOMER 2503,BR,SP,Araraquara,Sorocaba,BL01-CA09-1063,Lubrificantes,CA09,2022-01-31,32888694,251,227.90
22315,2500,CUSTOMER 2500,BR,SP,Araraquara,Sorocaba,BL01-CA03-1040,Lubrificantes,CA03,2022-01-31,32883619,35,365.05
24101,2503,CUSTOMER 2503,BR,SP,Araraquara,Sorocaba,BL01-CA03-1040,Lubrificantes,CA03,2022-01-31,32883617,60,85.71
25062,2503,CUSTOMER 2503,BR,SP,Araraquara,Sorocaba,BL01-CA11-1073,Lubrificantes,CA11,2022-01-31,32894385,458,355.30
...,...,...,...,...,...,...,...,...,...,...,...,...,...
20899,2494,CUSTOMER 2494,BR,SP,Araraquara,Sorocaba,BL01-CA10-1033,Lubrificantes,CA10,2022-01-03,32890039,95,2743.22
24823,2503,CUSTOMER 2503,BR,SP,Araraquara,Sorocaba,BL01-CA09-1063,Lubrificantes,CA09,2022-01-03,32887129,1004,911.60
22433,2500,CUSTOMER 2500,BR,SP,Araraquara,Sorocaba,BL01-CA04-1042,Lubrificantes,CA04,2022-01-03,32890781,458,390.72
23067,2500,CUSTOMER 2500,BR,SP,Araraquara,Sorocaba,BL01-CA06-1051,Lubrificantes,CA06,2022-01-03,32883721,522,135.60
23068,2500,CUSTOMER 2500,BR,SP,Araraquara,Sorocaba,BL01-CA06-1051,Lubrificantes,CA06,2022-01-03,32883775,4698,505.74

#### Métodos Aplicadas ao Dataframe

In [ ]:
sorocaba_df.tail() # traz os últimos itens da tabela (padrão 5)

# head e tail sao metodos que podem ser utilizados para uma visualização rápida do dataframe, mas não são métodos de filtragem, apenas de visualização

,CustomerNumber,CustomerName,Country,State,City,PlantName,MaterialNumber,BusinessLine,Category,SalesDate,SalesOrder,Volume,Revenue
25735,2506,CUSTOMER 2506,BR,SP,Araraquara,Sorocaba,BL02-CA03-2185,Aditivos,CA03,2021-04-28,32726874,0,3391.20
25736,2506,CUSTOMER 2506,BR,SP,Araraquara,Sorocaba,BL02-CA03-2185,Aditivos,CA03,2021-07-29,32785472,0,154.98
25737,2506,CUSTOMER 2506,BR,SP,Araraquara,Sorocaba,BL02-CA03-2186,Aditivos,CA03,2020-06-11,32532779,0,297.26
25738,2506,CUSTOMER 2506,BR,SP,Araraquara,Sorocaba,BL02-CA03-2186,Aditivos,CA03,2022-03-15,32938089,0,0.45
25739,2506,CUSTOMER 2506,BR,SP,Araraquara,Sorocaba,BL02-CA03-2186,Aditivos,CA03,2022-07-08,33011478,0,9.54

In [78]:
soma_vendas_sorocaba = sorocaba_df['Revenue'].sum() # soma todos os valores da coluna Revenue do dataframe sorocaba_df

print(soma_vendas_sorocaba)

8030349.42

In [79]:
sorocaba_df['Revenue'].sort_values(ascending=False).head() # Ordena os valores da coluna Revenue do dataframe sorocaba_df em ordem decrescente

22503    122867.64
22504     64763.77
14022     43500.94
22505     39480.00
23299     35983.65
Name: Revenue, dtype: float64

In [80]:
sorocaba_df.sort_values(by='Revenue', ascending=False).head()
# Ordena pela coluna Revenue do dataframe sorocaba_df em ordem decrescente, mas traz todas as colunas do dataframe

,CustomerNumber,CustomerName,Country,State,City,PlantName,MaterialNumber,BusinessLine,Category,SalesDate,SalesOrder,Volume,Revenue
22503,2500,CUSTOMER 2500,BR,SP,Araraquara,Sorocaba,BL01-CA06-1030,Lubrificantes,CA06,2022-05-31,32960588,64790,122867.64
22504,2500,CUSTOMER 2500,BR,SP,Araraquara,Sorocaba,BL01-CA06-1030,Lubrificantes,CA06,2022-09-08,33032625,34151,64763.77
14022,2467,CUSTOMER 2467,BR,SP,Araçariguama,Sorocaba,BL01-CA09-1064,Lubrificantes,CA09,2021-11-15,32860431,0,43500.94
22505,2500,CUSTOMER 2500,BR,SP,Araraquara,Sorocaba,BL01-CA06-1030,Lubrificantes,CA06,2022-11-03,33068813,18736,39480.00
23299,2500,CUSTOMER 2500,BR,SP,Araraquara,Sorocaba,BL01-CA06-1052,Lubrificantes,CA06,2020-05-28,32506870,20500,35983.65

In [81]:
maior_venda_sorocaba = sorocaba_df['Revenue'].max() # retorna o maior valor da coluna Revenue do dataframe sorocaba_df
print(maior_venda_sorocaba)

122867.64

In [53]:
menor_venda_sorocaba = sorocaba_df['Revenue'].min() # retorna o menor valor da coluna Revenue do dataframe sorocaba_df
print(menor_venda_sorocaba)

-29810.5

In [95]:
media_vendas_sorocaba = sorocaba_df['Revenue'].mean() # retorna a média dos valores da coluna Revenue do dataframe sorocaba_df
print(f"{media_vendas_sorocaba:.2f}")

1020.89

In [104]:
mediana_vendas_sorocaba = sorocaba_df['Revenue'].median() # retorna a mediana dos valores da coluna Revenue do dataframe sorocaba_df

# a diferencia entre media e mediana é que a media é a soma de todos os valores dividido pela quantidade de valores, 
# enquanto a mediana é o valor que está no meio da lista de valores ordenados.

print(mediana_vendas_sorocaba)

369.52

In [83]:
quantidade_vendas_sorocaba = sorocaba_df['Revenue'].count() # retorna a quantidade de vendas (linhas) da coluna Revenue do dataframe sorocaba_df
print(quantidade_vendas_sorocaba)

7866

In [103]:
quantidade_valoresUnicos_vendas_sorocaba = sorocaba_df['Revenue'].nunique()

print(quantidade_valoresUnicos_vendas_sorocaba)

4695

In [101]:
valoresUnicos_vendas_sorocaba = sorocaba_df['Revenue'].unique() # retorna os valores únicos da coluna Revenue do dataframe sorocaba_df

print(valoresUnicos_vendas_sorocaba)

[305.65 133.95  57.58 ... 297.26   0.45   9.54]

In [ ]:
sorocaba_df['Revenue'].std() # retorna o desvio padrão dos valores da coluna Revenue do dataframe sorocaba_df

# o desvio padrão é uma medida de dispersão que indica o quanto os valores de um conjunto de dados se afastam da média. 
# Quanto maior o desvio padrão, maior a variabilidade dos dados em relação à média.

np.float64(2894.3325659363063)

#### Group By

In [41]:
sorocaba_df.groupby('Category')['Revenue'].sum().sort_values(ascending=False)
# groupby é para agrupar por uma coluna, e o ['Revenue'] é para definir a coluna que será somada, 
# e o .sum() é uma função para somar os valores da coluna definida

Category
CA04    2113560.41
CA06    1538297.66
CA09    1152485.33
CA01     849513.65
CA11     823863.80
CA10     603417.01
CA07     446650.34
CA03     322674.78
CA02     117107.32
CA05      54003.57
CA08       8775.55
Name: Revenue, dtype: float64

In [108]:
sorocaba_df_group = sorocaba_df.groupby(['BusinessLine', 'Category'])['Revenue'].sum().sort_values(ascending=False) 
# groupby com lista de colunas, para agrupar por mais de uma coluna, e o ['Revenue'] é para definir a coluna que será somada.
sorocaba_df_group

BusinessLine   Category
Lubrificantes  CA04        2113560.41
               CA06        1538297.66
               CA09        1152485.33
Aditivos       CA01         849513.65
Lubrificantes  CA11         823863.80
               CA10         603417.01
               CA07         446650.34
               CA03         274446.23
Aditivos       CA02         117107.32
Lubrificantes  CA05          54003.57
Aditivos       CA03          48228.55
Lubrificantes  CA08           8775.55
Name: Revenue, dtype: float64

In [112]:
sorocaba_df_group.reset_index() # reseta o index do dataframe, transformando os valores do index em colunas do dataframe

     BusinessLine Category     Revenue
0   Lubrificantes     CA04  2113560.41
1   Lubrificantes     CA06  1538297.66
2   Lubrificantes     CA09  1152485.33
3        Aditivos     CA01   849513.65
4   Lubrificantes     CA11   823863.80
5   Lubrificantes     CA10   603417.01
6   Lubrificantes     CA07   446650.34
7   Lubrificantes     CA03   274446.23
8        Aditivos     CA02   117107.32
9   Lubrificantes     CA05    54003.57
10       Aditivos     CA03    48228.55
11  Lubrificantes     CA08     8775.55

#### Tabelas Dinâmicas

In [126]:
df.pivot_table(
    index='State', # define a coluna que será utilizada como index (linhas) da tabela dinâmica
    columns='Category', # define a coluna que será utilizada como colunas da tabela dinâmica
    values='Revenue', # define a coluna que será utilizada como valores da tabela dinâmica
    aggfunc='sum', # define a função de agregação que será utilizada para os valores da tabela dinâmica
    margins=True, # define se será exibido o total geral da tabela dinâmica
    margins_name='Total' # define o nome da coluna do total geral da tabela dinâmica
)

Category,CA01,CA02,CA03,CA04,CA05,CA06,CA07,CA08,CA09,CA10,CA11,Total
State,,,,,,,,,,,,
BA,26298.01,9091.70,4997.87,105653.97,1468.96,79941.86,27572.16,130.00,66523.20,10715.38,43945.34,376338.45
GO,223901.30,120929.91,693024.62,677750.70,248067.35,3946167.63,139831.06,17728.64,102534.50,251948.65,3120492.10,9542376.46
MG,240047.69,75459.08,136724.92,259865.04,238185.92,702807.37,308804.06,8138.72,132637.48,65780.79,179271.00,2347722.07
PR,406455.87,118215.25,946415.97,624692.95,85756.27,1165299.68,500180.98,30996.01,399501.37,386924.70,633330.42,5297769.47
SC,277348.24,16737.87,127941.73,591518.62,70167.45,870041.86,138994.05,15818.62,271044.83,162838.76,523235.00,3065687.03
SP,849513.65,117107.32,322674.78,2113560.41,54003.57,1538297.66,446650.34,8775.55,1152485.33,603417.01,823863.80,8030349.42
Total,2023564.76,457541.13,2231779.89,4373041.69,697649.52,8302556.06,1562032.65,81587.54,2124726.71,1481625.29,5324137.66,28660242.90